### ISSUE TITLE
大大，请问该项目是否支持windows系统下对文档中的敏感字体扫描？

### ISSUE THREAD

**Issue by hongyuXie** [repoog/GitPrey#10]
场景是这样的：由于某些字体后期采用了付费策略，现在想通过扫描历史文档中的字体是否采用了某些收费的字体

**Comment by repoog** [comment]
首先看是否有固定的文件格式，其次看是否有固定的文件内容，有其一，即可检索。

**Comment by hongyuXie** [comment]
文件格式是:office的word文档和excel文档,需要扫描遍历操作系统上的这两类文档,识别文档中是否使用某种字体,如:宋体或者其它字体等

固定的文件内容指的是?

**Comment by repoog** [comment]
这个项目无法检索office文档中的字体类型
