### ISSUE TITLE
扫描中的问题

### ISSUE THREAD

**Issue by henryhjx** [repoog/GitPrey#12]
[!_!] ERROR INFO: There is 'HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /p4int3r/Tools/f4107e4a9f2f4ba13492a0478f697f239a515f3c/golismero/golismero/api/config.py (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f26aeca6050>, 'Connection to raw.githubusercontent.com timed out. (connect timeout=10)'))' problem in requesting html page.

扫描到一半提示这个错误

**Comment by repoog** [comment]
可以降低并发次数，或者增加重连次数来尝试解决。
