### ISSUE TITLE
扫描结果展示问题

### ISSUE THREAD

**Issue by xiaopopoxiao** [repoog/GitPrey#14]
作者你好，不知道是我没找到还是确实没这功能，扫描完毕之后，只能在log文件中查看到结果的蛛丝马迹，感觉这样很难通过扫描结果来判断漏洞，不知道扫描结果作者是怎么组织的？

**Comment by repoog** [comment]
@xiaopopoxiao 工具只能帮助寻找疑似的项目及代码，需要结合人工的检查来确认，我们自己使用时是将输出展现在数据库中，可视化的方式来检查，会方便一些，但依然免不了对每个项目的具体确认。
