### ISSUE TITLE
colorama 未找到，但已经安装过

### ISSUE THREAD

**Issue by ycjcl868** [repoog/GitPrey#15]
```
$ sudo pip install colorama
$ python GitPrey.py
[!_!]ERROR INFO: You have to install colorama module.
```

**Comment by poppyzzz** [comment]
similar error, for requests module.

**Comment by repoog** [comment]
请确认是否是python 2.7版本，之后会升级到python 3.6版本。

**Comment by 2879** [comment]
我是python2.7，可是也报错[!_!]ERROR INFO: You have to install requests module. 
![image](https://user-images.githubusercontent.com/10540934/44714139-259ccb00-aae7-11e8-8c2d-0330a457b497.png)

**Comment by hu-qi** [comment]
重装就ok @2879 
我遇到同样的问题 重装就可以了
![image](https://user-images.githubusercontent.com/17986122/44946963-7b9ba680-ae38-11e8-84df-e541c549c8f8.png)
