### ISSUE TITLE
There is 'HTTPSConnectionPool(host='github.com', port=443): Read timed out

### ISSUE THREAD

**Issue by hu-qi** [repoog/GitPrey#17]
虽然已经停更了，还是要请教一下大佬，有没有遇到以下情况：
![image](https://user-images.githubusercontent.com/17986122/44947035-7428cd00-ae39-11e8-9ba8-982ea146bb05.png)

**Comment by repoog** [comment]
访问超时，可以尝试把代码中的暂停时间加长。
另外，没有停更，只是一直没时间更新版本，十一左右会更新到3.6版本。
