### ISSUE TITLE
github登陆失败

### ISSUE THREAD

**Issue by Mrhhhhhhx** [repoog/GitPrey#19]
在config文件里设置了正确的账户密码，却显示登录不了，需要输入Verification code

**Comment by repoog** [comment]
看下浏览器登录时登录框是否需要输入验证码，可能是多次登录失败后需要输入验证码。

**Comment by sqlsec** [comment]
同遇到登录失败的问题了 在config文件里设置了正确的账户密码，却显示登录不了
```r
[!] Error: Login Github failed, please check account in config file.
```

**Comment by repoog** [comment]
> 同遇到登录失败的问题了 在config文件里设置了正确的账户密码，却显示登录不了
> 
> ```r
> [!] Error: Login Github failed, please check account in config file.
> ```

检查下用户名密码是否正确，可以手动在网页中登录测试下。
