### ISSUE TITLE
[!] Error: Login Github failed, please check account in config file.

### ISSUE THREAD

**Issue by qiumin1003** [repoog/GitPrey#20]
配置文件都是对的，登录不上去

**Comment by repoog** [comment]
> 配置文件都是对的，登录不上去

可以手动测试下配置的账户信息对不对。

**Comment by twosmi1e** [comment]
原因好像是因为验证码问题，如果不用常用设备登录会发验证码

**Comment by AdministratorGithub** [comment]
![image](https://user-images.githubusercontent.com/19834937/78959077-6dd1fb00-7b1c-11ea-9209-5bb2e5871ef5.png)
  因为设备问题，解决方式：  
  1.跟换ua头  
  2.注释登录模块，类cookies手动设置

**Comment by AdministratorGithub** [comment]
另外ip地址要和你vpn或者ssr的一样，这是github的问题，不是代码的问题
