### ISSUE TITLE
对项目的一点困惑

### ISSUE THREAD

**Issue by zhangzhenfeng** [repoog/GitPrey#22]
我看项目并没有使用searchapi，是不好用吗？还是什么原因，因为我在使用您的项目时出现了搜索不到的问题，具体代码是在BeautifulSoup处理a.text-bold时，并没有匹配到，github将a.text-bold属性都放到了div中。还请抽空解答下我的疑问，谢谢。

**Comment by repoog** [comment]
刚开始用的是github的API，好处是API的向下兼容好，对于项目信息的获取简单直接，但缺陷是API的调用频率有限制，而我希望更快的获取到信息，所以改用了爬虫方式，但缺点也如你所说，需要根据GitHub的更新来更新爬虫的代码。
