### ISSUE TITLE
project_info = cur_par_html.select("p.title > a:nth-of-type(1)") 失效了

### ISSUE THREAD

**Issue by lfzark** [repoog/GitPrey#8]
不知道project_info原来解析出来的是什么内容,所以没办法fix

**Comment by repoog** [comment]
GitHub做了升级，所以也要做相应升级，正在着手进行GitPrey的升级开发，新版本会增加和弥补之前版本的遗留未做的功能和遗憾。

**Comment by repoog** [comment]
已更新版本支持最新GitHub检索。
