### ISSUE TITLE
关键字问题

### ISSUE THREAD

**Issue by kulozzzz** [repoog/GitPrey#9]
我想问一下在这个程序里面-k 是设置关键字的参数，然后info.db里面也是设置关键字的，我想问一下这个搜索关键字是按照-k传进去的搜索还是去读取info.db搜索啊。

**Comment by repoog** [comment]
-k参数的关键字是搜索项目时候的关键字，即项目关键字。info.db的关键字是项目中敏感内容的关键字，即敏感信息关键字。两个都会用到，先基于项目关键字检索项目，然后再基于敏感信息关键字在项目中检索，因为有些项目虽然有项目关键字，但只是引用或提到，并不存在敏感信息的情况。

**Comment by kulozzzz** [comment]
但是我不想指定那个项目区搜索，要全github去搜索我想要的关键字这个我该怎么弄呢？

**Comment by repoog** [comment]
本质上程序还是模拟人工搜索的过程，如果不想指定项目范围的话，最好的办法是直接在GitHub中进行人工搜索。限制项目范围是为了缩小项目搜索范围从而节省时间。
